### ISSUE TITLE
Provide layout designs for discussion

### ISSUE THREAD

**Issue by riiski** [VilniusTechmap/vilniustechmap.github.io#13]

**Comment by RiskLTU** [comment]
My first try
![artboard 1](https://cloud.githubusercontent.com/assets/7087900/11957045/8ea08cec-a8c7-11e5-8a56-3eeff9c0c961.png)

**Comment by riiski** [comment]
![artboard 1_2](https://cloud.githubusercontent.com/assets/7087900/11957526/ec35ad1c-a8ca-11e5-94ec-9c2bc8f1e0e4.png)

**Comment by tadas-subonis** [comment]
Expired
